### ISSUE TITLE
Issue-Initial pass of main API endpoints

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/test2#4]
Automated Review Comments
Issues in README.rst:
  - (5, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (130, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (142, 'TODO found')
Issues in binance/client.py:
  - (28, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (129, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (143, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (168, 'Line exceeds 80 characters')
  - (173, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (206, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (227, 'Line exceeds 80 characters')
  - (233, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
Issues in binance/enums.py:
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in binance/exceptions.py:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in setup.py:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
